server:
  port: 8080

zuul:
  routes:
    testerotas1:  #Aqui é a rota "/testerotas" que passará para "http://localhost:8090"
      path: /testerotas/**
      url: http://localhost:8090



ribbon:
  eureka:
    enabled: false



