package br.com.hoiama;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Controller
@SpringBootApplication
public class EndPoint {
    public static void main(String[] args) {
        SpringApplication.run(EndPoint.class, args);
    }

    @ResponseBody
    @RequestMapping(value="/", method= RequestMethod.GET)
    public String getTeste(){
        return "testando página";
    }



}
