package br.com.hoiama;

import br.com.hoiama.filtros.PostFilter;
import br.com.hoiama.filtros.PreFilter;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;
import org.springframework.context.annotation.Bean;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@EnableZuulProxy
@SpringBootApplication
public class Zuul {
    public static void main(String[] args) {
        SpringApplication.run(Zuul.class, args);
    }


    @Bean
    public PreFilter preFilter(){
        return new PreFilter();
    }

    @Bean
    public PostFilter postFilter(){
        return postFilter();
    }
}
